name = "LFDTD"
uuid = "d55ded6f-cac3-4489-b836-163dee203dc0"
authors = ["Alejandro Luque <aluque@iaa.es> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
